# Generated by Django 3.2 on 2022-10-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddrees',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userphonenumber',
            name='type',
        ),
        migrations.AddField(
            model_name='useraddrees',
            name='data_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userphonenumber',
            name='data_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
