# Generated by Django 3.2 on 2022-09-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85, verbose_name='Company Name')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Company Logo')),
                ('call_us', models.CharField(max_length=50, verbose_name='Company Number')),
                ('email_us', models.EmailField(max_length=254, verbose_name='Company Email')),
                ('sub_title', models.CharField(max_length=500, verbose_name='About Company')),
                ('tw_link', models.URLField(verbose_name='Tweiter')),
                ('lk_in_link', models.URLField(verbose_name='Linked in')),
                ('fb_link', models.URLField(verbose_name='FaceBook')),
                ('ista_link', models.URLField(verbose_name='Istagram')),
                ('Addrees', models.TextField(max_length=100, verbose_name='')),
                ('Cphone', models.TextField(max_length=100, verbose_name='')),
                ('conct_us', models.TextField(max_length=100, verbose_name='')),
            ],
        ),
    ]
