# Generated by Django 3.2 on 2022-11-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('receved', 'received'), ('processed', 'prosessed'), ('shiped', 'shiped'), ('delivered', 'delivered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('receved', 'received'), ('processed', 'prosessed'), ('shiped', 'shiped'), ('delivered', 'delivered')], max_length=50),
        ),
    ]
