# Generated by Django 3.2 on 2022-11-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_carddetail_quantaty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carddetail',
            old_name='quantaty',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
