# Generated by Django 3.2 on 2022-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221109_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
