# Generated by Django 3.2 on 2022-11-14 10:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_quantity'),
        ('orders', '0006_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CardDetail',
            new_name='CartDetail',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='card',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartdetail',
            old_name='card',
            new_name='cart',
        ),
    ]
