# Generated by Django 3.2 on 2022-10-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220905_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=50, verbose_name='Quantity'),
        ),
    ]
